version: '3'

services:
  docker-tutorial:
    restart: always
    build: .
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NAME: "bad boy"
      REDIS_CON_TYPE: "tcp"
      REDIS_CONNECTION: "redis:6379"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"